import { useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarDays, Search } from 'lucide-react'
import { Page } from '../components/Page'
import { useAccess } from '../components/AuthorizedAccess'
import { supabase } from '../lib/supabase'
type Event={id:string;title:string;description:string|null;starts_at:string;cancelled_at:string|null;sync_status:string;client:{name:string}|null;order:{display_number:string}|null}
export function Calendar(){
 const access=useAccess(),[events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[history,setHistory]=useState(false)
 const load=useCallback(async()=>{if(!supabase||!access)return;setLoading(true);setError('');let query=supabase.from('calendar_events').select('id,title,description,starts_at,cancelled_at,sync_status,client:clients!calendar_events_client_id_fkey(name),order:orders!calendar_events_order_id_fkey(display_number)').eq('organization_id',access.organizationId).order('starts_at',{ascending:true}).limit(300);if(!history)query=query.is('cancelled_at',null).gte('starts_at',new Date(new Date().setHours(0,0,0,0)).toISOString());const {data,error}=await query.abortSignal(AbortSignal.timeout(15000));if(error)setError('Não foi possível carregar a agenda.');else setEvents((data??[]) as unknown as Event[]);setLoading(false)},[access,history])
 useEffect(()=>{void load()},[load])
 const filtered=useMemo(()=>{const term=search.trim().toLocaleLowerCase('pt-BR');return term?events.filter(x=>`${x.title} ${x.description??''} ${x.client?.name??''}`.toLocaleLowerCase('pt-BR').includes(term)):events},[events,search])
 const today=new Date().toDateString(),todayCount=events.filter(x=>new Date(x.starts_at).toDateString()===today&&!x.cancelled_at).length,pending=events.filter(x=>x.sync_status==='pending'&&!x.cancelled_at).length
 return <Page title="Agenda" description="Compromissos operacionais vinculados diretamente aos itens dos pedidos."><section className="status-grid"><article><span>Compromissos exibidos</span><strong>{filtered.length}</strong></article><article><span>Hoje</span><strong>{todayCount}</strong></article><article><span>Aguardando sincronização</span><strong>{pending}</strong></article><article><span>Origem</span><strong>Pedidos</strong></article></section><section className="panel"><div className="toolbar"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cliente, pedido, ambiente ou descrição"/></label><div className="segmented"><button className={!history?'active':''} onClick={()=>setHistory(false)}>Próximos</button><button className={history?'active':''} onClick={()=>setHistory(true)}>Histórico</button></div></div>{error?<div className="empty-state"><CalendarDays/><strong>{error}</strong><button className="button secondary" onClick={()=>void load()}>Tentar novamente</button></div>:loading?<p className="panel-message">Carregando agenda…</p>:filtered.length?<div className="table-wrap"><table><thead><tr><th>Data e hora</th><th>Compromisso</th><th>Cliente</th><th>Pedido</th><th>Google Calendar</th></tr></thead><tbody>{filtered.map(event=><tr key={event.id} className={event.cancelled_at?'cancelled-row':''}><td><strong>{new Date(event.starts_at).toLocaleDateString('pt-BR')}</strong><small className="table-subline">{new Date(event.starts_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></td><td><strong>{event.title}</strong><small className="table-subline">{event.description||'Sem observações'}</small></td><td>{event.client?.name??'—'}</td><td>{event.order?.display_number??'—'}</td><td><span className="badge">{event.cancelled_at?'Cancelamento pendente':event.sync_status==='synced'?'Sincronizado':'Pendente'}</span></td></tr>)}</tbody></table></div>:<div className="empty-state"><CalendarDays/><strong>Nenhum compromisso encontrado</strong><span>Ao agendar um item do pedido, ele aparecerá aqui automaticamente.</span></div>}</section></Page>
}
