import { useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarDays, RefreshCw, Search } from 'lucide-react'
import { Page } from '../components/Page'
import { useAccess } from '../components/AuthorizedAccess'
import { useToast } from '../components/ToastProvider'
import { sendToGoogle, type SyncEvent } from '../lib/googleCalendar'
import { supabase } from '../lib/supabase'
import {calendarSyncStatuses,needsCalendarSync} from '../lib/calendarStatus'
import { applicationRedirectUrl } from '../lib/authUrl'
type Event=SyncEvent&{sync_status:string;client:{name:string}|null;order:{display_number:string}|null}
export function Calendar(){
 const access=useAccess(),{show}=useToast(),[events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[history,setHistory]=useState(false),[syncing,setSyncing]=useState(false)
 const canSync=access?.role==='admin'||access?.role==='operacao',connected=Boolean(sessionStorage.getItem('fk_google_provider_token'))
 const load=useCallback(async()=>{if(!supabase||!access)return;setLoading(true);setError('');let query=supabase.from('calendar_events').select('id,title,description,starts_at,ends_at,cancelled_at,google_event_id,sync_status,client:clients!calendar_events_client_id_fkey(name),order:orders!calendar_events_order_id_fkey(display_number)').eq('organization_id',access.organizationId).order('starts_at',{ascending:true}).limit(300);if(!history)query=query.is('cancelled_at',null).gte('starts_at',new Date(new Date().setHours(0,0,0,0)).toISOString());const {data,error}=await query.abortSignal(AbortSignal.timeout(15000));if(error)setError('Não foi possível carregar a agenda.');else setEvents((data??[]) as unknown as Event[]);setLoading(false)},[access,history])
 useEffect(()=>{void load()},[load])
 const connect=async()=>{if(!supabase)return;await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:applicationRedirectUrl(window.location.origin,import.meta.env.BASE_URL),scopes:'https://www.googleapis.com/auth/calendar.events',queryParams:{access_type:'offline',prompt:'consent'}}})}
 const sync=async()=>{if(!supabase||!access||syncing)return;const token=sessionStorage.getItem('fk_google_provider_token');if(!token){await connect();return}setSyncing(true);const {data,error}=await supabase.from('calendar_events').select('id,title,description,starts_at,ends_at,cancelled_at,google_event_id').eq('organization_id',access.organizationId).in('sync_status',[...calendarSyncStatuses]).limit(100);if(error){show('Não foi possível consultar os compromissos pendentes.','error');setSyncing(false);return}let failures=0;for(const event of (data??[]) as SyncEvent[]){try{const result=await sendToGoogle(event,token);const {error:markError}=await supabase.rpc('mark_calendar_event_sync',{org_id:access.organizationId,target_event_id:event.id,new_google_event_id:result.googleEventId??'',new_status:'synced'});if(markError)throw markError}catch(reason){failures++;if(reason instanceof Error&&reason.message==='reauthorize'){sessionStorage.removeItem('fk_google_provider_token');show('A autorização do Google expirou. Conecte novamente.','error');break}await supabase.rpc('mark_calendar_event_sync',{org_id:access.organizationId,target_event_id:event.id,new_google_event_id:event.google_event_id??'',new_status:'error'})}}setSyncing(false);await load();if(!failures)show('Agenda sincronizada com o Google Calendar.','success');else show(`${failures} compromisso(s) não puderam ser sincronizados. A próxima sincronização tentará novamente.`,'error')}
 const filtered=useMemo(()=>{const term=search.trim().toLocaleLowerCase('pt-BR');return term?events.filter(x=>`${x.title} ${x.description??''} ${x.client?.name??''}`.toLocaleLowerCase('pt-BR').includes(term)):events},[events,search])
 const today=new Date().toDateString(),todayCount=events.filter(x=>new Date(x.starts_at).toDateString()===today&&!x.cancelled_at).length,pending=events.filter(x=>needsCalendarSync(x.sync_status)&&!x.cancelled_at).length
 const action=canSync?<button className="button primary" disabled={syncing} onClick={()=>void(connected?sync():connect())}><RefreshCw/>{syncing?'Sincronizando…':connected?'Sincronizar Google':'Conectar Google Calendar'}</button>:undefined
 return <Page title="Agenda" description="Compromissos operacionais vinculados diretamente aos itens dos pedidos." action={action}><section className="status-grid"><article><span>Compromissos exibidos</span><strong>{filtered.length}</strong></article><article><span>Hoje</span><strong>{todayCount}</strong></article><article><span>Aguardando sincronização</span><strong>{pending}</strong></article><article><span>Google Calendar</span><strong>{connected?'Conectado':'Desconectado'}</strong></article></section><section className="panel"><div className="toolbar"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cliente, pedido, ambiente ou descrição"/></label><div className="segmented"><button className={!history?'active':''} onClick={()=>setHistory(false)}>Próximos</button><button className={history?'active':''} onClick={()=>setHistory(true)}>Histórico</button></div></div>{error?<div className="empty-state"><CalendarDays/><strong>{error}</strong><button className="button secondary" onClick={()=>void load()}>Tentar novamente</button></div>:loading?<p className="panel-message">Carregando agenda…</p>:filtered.length?<div className="table-wrap"><table><thead><tr><th>Data e hora</th><th>Compromisso</th><th>Cliente</th><th>Pedido</th><th>Google Calendar</th></tr></thead><tbody>{filtered.map(event=><tr key={event.id} className={event.cancelled_at?'cancelled-row':''}><td><strong>{new Date(event.starts_at).toLocaleDateString('pt-BR')}</strong><small className="table-subline">{new Date(event.starts_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></td><td><strong>{event.title}</strong><small className="table-subline">{event.description||'Sem observações'}</small></td><td>{event.client?.name??'—'}</td><td>{event.order?.display_number??'—'}</td><td><span className="badge">{event.cancelled_at?'Cancelamento pendente':event.sync_status==='synced'?'Sincronizado':event.sync_status==='error'?'Falha':'Pendente'}</span></td></tr>)}</tbody></table></div>:<div className="empty-state"><CalendarDays/><strong>Nenhum compromisso encontrado</strong><span>Ao agendar um item do pedido, ele aparecerá aqui automaticamente.</span></div>}</section></Page>
}
