import {useCallback,useEffect,useMemo,useState} from 'react'
import {PackageCheck,Search} from 'lucide-react'
import {Page} from '../components/Page'
import {OrderDetails,type DetailOrder} from '../components/OrderDetails'
import {OrderCancellation} from '../components/OrderCancellation'
import {OrderOperation} from '../components/OrderOperation'
import {useAccess} from '../components/AuthorizedAccess'
import {money} from '../lib/format'
import {operationalStatuses,orderStatusLabels as labels,orderStatusOptions,type OrderStatus} from '../lib/orderStatus'
import {supabase} from '../lib/supabase'
import {navigateTo,readRoute} from '../lib/navigation'
import './Orders.css'
type Order=DetailOrder&{status:OrderStatus}
export function Orders(){
 const access=useAccess(),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[cancelOrder,setCancelOrder]=useState<Order|null>(null),[operationOrder,setOperationOrder]=useState<Order|null>(null),[requestedStage,setRequestedStage]=useState<(typeof operationalStatuses)[number]>('preparing')
 const load=useCallback(async()=>{if(!supabase||!access)return;setLoading(true);setError('');const{data,error}=await supabase.from('orders').select('id,display_number,status,payment_terms,promised_date,client_address,total,created_at,client:clients!orders_client_id_fkey(name,phone,address,city),budget:budgets!orders_budget_id_fkey(display_number),order_items:order_items!order_items_order_id_fkey(id,status,snapshot),receivables:receivables!receivables_order_id_fkey(id,installment,installment_count,due_date,amount,payment_method,status)').eq('organization_id',access.organizationId).order('number',{ascending:false}).abortSignal(AbortSignal.timeout(15000));if(error)setError('Não foi possível carregar os pedidos. Tente novamente.');else setOrders((data??[])as unknown as Order[]);setLoading(false)},[access])
 useEffect(()=>{void load()},[load])
 const detailId=readRoute(window.location.hash).recordId,detailOrder=detailId?orders.find(order=>order.id===detailId)??null:null
 const filtered=useMemo(()=>{const term=search.trim().toLocaleLowerCase('pt-BR');return term?orders.filter(x=>`${x.display_number} ${x.client?.name??''} ${x.budget?.display_number??''} ${labels[x.status]}`.toLocaleLowerCase('pt-BR').includes(term)):orders},[orders,search])
 const requestStatus=(order:Order,next:OrderStatus)=>{if(next===order.status)return;if(next==='cancelled'){setCancelOrder(order);return}if((operationalStatuses as readonly string[]).includes(next)){setRequestedStage(next as (typeof operationalStatuses)[number]);setOperationOrder(order)}}
 const active=orders.filter(x=>!['completed','cancelled'].includes(x.status)).length,awaitingPurchase=orders.filter(x=>x.status==='awaiting_purchase').length,scheduling=orders.filter(x=>x.status==='ready_to_schedule').length,issues=orders.filter(x=>x.status==='pending_issue').length
 if(detailId){return <Page title="Pedido" description="Itens, valores, entrega e recebimento do pedido em uma única tela.">{loading?<p className="panel-message">Carregando pedido…</p>:detailOrder&&access?<OrderDetails organizationId={access.organizationId} order={detailOrder} onBack={()=>navigateTo('pedidos')} onSaved={load}/>:<div className="empty-state"><PackageCheck/><strong>Pedido não encontrado</strong><button className="button secondary" onClick={()=>navigateTo('pedidos')}>Voltar aos pedidos</button></div>}</Page>}
 return <Page title="Pedidos" description="Toda a operação acompanha o pedido e seus itens — sem módulos separados de produção e entrega.">{cancelOrder&&access&&<OrderCancellation organizationId={access.organizationId} order={cancelOrder} onClose={()=>setCancelOrder(null)} onSaved={load}/>} {operationOrder&&access&&<OrderOperation organizationId={access.organizationId} order={operationOrder} initialStage={requestedStage} onClose={()=>setOperationOrder(null)} onSaved={load}/>}<section className="status-grid"><article><span>Ativos</span><strong>{active}</strong></article><article><span>Aguardando compra</span><strong>{awaitingPurchase}</strong></article><article><span>Para agendar</span><strong>{scheduling}</strong></article><article><span>Com pendência</span><strong>{issues}</strong></article></section><section className="panel"><div className="toolbar"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pedido, orçamento, cliente ou status"/></label><span>{filtered.length} pedido(s)</span></div>{error?<div className="empty-state"><PackageCheck/><strong>{error}</strong><button className="button secondary" onClick={()=>void load()}>Tentar novamente</button></div>:loading?<p className="panel-message">Carregando pedidos…</p>:filtered.length?<div className="table-wrap"><table><thead><tr><th>Pedido / cliente</th><th>Origem</th><th>Criação</th><th>Entrega ao cliente</th><th>Itens</th><th>Valor</th><th>Status</th></tr></thead><tbody>{filtered.map(order=><tr className="clickable-row" key={order.id} onClick={()=>navigateTo('pedidos',order.id)}><td><strong>{order.display_number}</strong><small>{order.client?.name??'Cliente não informado'}</small></td><td>{order.budget?.display_number??'—'}</td><td>{new Date(order.created_at).toLocaleDateString('pt-BR')}</td><td>{order.promised_date?new Date(`${order.promised_date}T12:00:00`).toLocaleDateString('pt-BR'):'A confirmar'}</td><td>{order.order_items.length}</td><td><strong>{money.format(Number(order.total))}</strong></td><td><select className="status-select" aria-label={`Status de ${order.display_number}`} value={order.status} onClick={e=>e.stopPropagation()} onChange={e=>{e.stopPropagation();requestStatus(order,e.target.value as OrderStatus)}}>{orderStatusOptions(order.status).map(status=><option value={status} key={status}>{labels[status]}</option>)}</select></td></tr>)}</tbody></table></div>:<div className="empty-state"><PackageCheck/><strong>Nenhum pedido neste ambiente</strong><span>Pedidos serão criados exclusivamente a partir de uma versão enviada e aprovada do orçamento.</span></div>}</section></Page>
}
