import { useState, type FormEvent } from 'react'
import { Boxes, Plus, Search, X } from 'lucide-react'
import { Page } from '../components/Page'
import { useCatalog } from '../lib/useCatalog'
import { money } from '../lib/format'
import { useToast } from '../components/ToastProvider'

type Supply={id:string;code:string;name:string;category:string;purchase_unit:string;usage_unit:string;current_cost:number;active:boolean}
const empty={code:'',name:'',category:'',purchase_unit:'un',usage_unit:'un',current_cost:0}
export function Supplies(){
 const catalog=useCatalog<Supply>('supplies','id,code,name,category,purchase_unit,usage_unit,current_cost,active')
 const {items}=catalog
 const [search,setSearch]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(empty);const {show}=useToast()
 const save=async(e:FormEvent)=>{e.preventDefault();try{if(await catalog.save(form)){show('Insumo salvo.','success');setOpen(false);setForm(empty)}}catch(error){show(error instanceof Error?error.message:'Não foi possível salvar.','error')}}
 const filtered=items.filter(x=>`${x.code} ${x.name} ${x.category}`.toLowerCase().includes(search.toLowerCase()))
 return <Page title="Insumos e produtos" description="Materiais usados diretamente nos itens, compras e custos." action={<button className="button primary" onClick={()=>setOpen(true)}><Plus/>Novo insumo</button>}>{catalog.loading && <p role="status">Carregando insumos…</p>}{catalog.error && <p role="alert">{catalog.error} <button className="button secondary" onClick={catalog.reload}>Tentar novamente</button></p>}<section className="panel"><div className="toolbar"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar código, nome ou categoria"/></label><span>{filtered.length} item(ns)</span></div><div className="table-wrap"><table><thead><tr><th>Código</th><th>Insumo/produto</th><th>Categoria</th><th>Compra</th><th>Uso</th><th>Custo atual</th><th>Status</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.code}</td><td><strong>{x.name}</strong></td><td>{x.category||'—'}</td><td>{x.purchase_unit}</td><td>{x.usage_unit}</td><td><strong>{money.format(x.current_cost)}</strong></td><td><span className={`badge ${x.active?'green':'muted'}`}>{x.active?'Ativo':'Inativo'}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-state compact"><Boxes/><strong>Nenhum insumo encontrado</strong></div>}</div></section>{open&&<div className="dialog-backdrop"><form className="dialog form-dialog" onSubmit={save}><header><div><span className="eyebrow">Cadastro utilizável</span><h2>Novo insumo ou produto</h2><p>Este registro poderá ser escolhido diretamente nos itens.</p></div><button type="button" className="icon-button" disabled={catalog.saving} onClick={()=>setOpen(false)}><X/></button></header><div className="form-grid"><label className="field">Código<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label className="field span-2">Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field">Categoria<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="field">Unidade de compra<input value={form.purchase_unit} onChange={e=>setForm({...form,purchase_unit:e.target.value})}/></label><label className="field">Unidade de uso<input value={form.usage_unit} onChange={e=>setForm({...form,usage_unit:e.target.value})}/></label><label className="field">Custo atual<input type="number" min="0" step="0.01" value={form.current_cost} onChange={e=>setForm({...form,current_cost:Number(e.target.value)})}/></label></div><footer><button type="button" className="button secondary" disabled={catalog.saving} onClick={()=>setOpen(false)}>Cancelar</button><button disabled={catalog.saving} className="button primary">{catalog.saving ? 'Salvando…' : 'Salvar insumo'}</button></footer></form></div>}</Page>
}
