import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { Plus, Search, Truck, X } from 'lucide-react'
import { Page } from '../components/Page'
import { useAccess } from '../components/AuthorizedAccess'
import { useToast } from '../components/ToastProvider'
import { supabase } from '../lib/supabase'

type Supplier={id:string;name:string;document:string|null;email:string|null;phone:string|null;supplier_types:string[];notes:string|null;active:boolean}
type Form={id?:string;name:string;document:string;email:string;phone:string;supplier_types:string;notes:string;active:boolean}
const blank:Form={name:'',document:'',email:'',phone:'',supplier_types:'',notes:'',active:true}

export function Suppliers(){
 const access=useAccess(),{show}=useToast(),[items,setItems]=useState<Supplier[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState<Form>(blank),[saving,setSaving]=useState(false)
 const load=useCallback(async()=>{if(!supabase||!access)return;setLoading(true);const {data,error}=await supabase.from('suppliers').select('id,name,document,email,phone,supplier_types,notes,active').eq('organization_id',access.organizationId).order('name');if(error)show('Não foi possível carregar os fornecedores.','error');else setItems((data??[]) as Supplier[]);setLoading(false)},[access,show])
 useEffect(()=>{void load()},[load])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?items.filter(x=>`${x.name} ${x.document??''} ${x.supplier_types.join(' ')}`.toLowerCase().includes(q)):items},[items,search])
 const edit=(x?:Supplier)=>{setForm(x?{id:x.id,name:x.name,document:x.document??'',email:x.email??'',phone:x.phone??'',supplier_types:x.supplier_types.join(', '),notes:x.notes??'',active:x.active}:blank);setOpen(true)}
 const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase||!access||saving)return;setSaving(true);const payload={organization_id:access.organizationId,name:form.name.trim(),document:form.document.trim()||null,email:form.email.trim()||null,phone:form.phone.trim()||null,supplier_types:form.supplier_types.split(',').map(x=>x.trim()).filter(Boolean),notes:form.notes.trim()||null,active:form.active};const result=form.id?await supabase.from('suppliers').update(payload).eq('organization_id',access.organizationId).eq('id',form.id):await supabase.from('suppliers').insert(payload);if(result.error)show(result.error.code==='42501'?'Seu perfil não pode alterar fornecedores.':'Não foi possível salvar o fornecedor.','error');else{setOpen(false);await load();show(form.id?'Fornecedor atualizado.':'Fornecedor cadastrado.','success')}setSaving(false)}
 return <Page title="Fornecedores" description="Base única para cotações, pedidos de compra e contas a pagar." action={<button className="button primary" onClick={()=>edit()}><Plus/>Novo fornecedor</button>}><section className="panel"><div className="toolbar"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, documento ou tipo fornecido"/></label><span>{filtered.length} fornecedor(es)</span></div>{loading?<p className="panel-message">Carregando fornecedores…</p>:filtered.length?<div className="table-wrap"><table><thead><tr><th>Fornecedor</th><th>Tipos atendidos</th><th>Contato</th><th>Documento</th><th>Situação</th></tr></thead><tbody>{filtered.map(x=><tr className="clickable-row" key={x.id} onClick={()=>edit(x)}><td><strong>{x.name}</strong></td><td>{x.supplier_types.length?x.supplier_types.join(', '):'Não informado'}</td><td>{x.phone||x.email||'—'}</td><td>{x.document||'—'}</td><td><span className={`badge ${x.active?'green':'muted'}`}>{x.active?'Ativo':'Inativo'}</span></td></tr>)}</tbody></table></div>:<div className="empty-state"><Truck/><strong>Nenhum fornecedor cadastrado</strong><span>Cadastre fornecedores para utilizá-los nos pedidos de compra.</span></div>}</section>{open&&<div className="dialog-backdrop"><form className="dialog" onSubmit={save}><header><div><span className="eyebrow">Cadastro</span><h2>{form.id?'Editar fornecedor':'Novo fornecedor'}</h2></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X/></button></header><div className="form-grid"><label className="field span-2">Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field">CPF/CNPJ<input value={form.document} onChange={e=>setForm({...form,document:e.target.value})}/></label><label className="field">Telefone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="field span-2">E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field span-2">Tipos fornecidos<input value={form.supplier_types} onChange={e=>setForm({...form,supplier_types:e.target.value})} placeholder="Ex.: Cortina, Persiana, Papel de parede"/><small>Separe os tipos por vírgula.</small></label><label className="field span-2">Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{form.id&&<label className="checkbox-field span-2"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Fornecedor ativo</label>}</div><footer><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="button primary" disabled={saving}>{saving?'Salvando…':'Salvar fornecedor'}</button></footer></form></div>}</Page>
}
