import { Printer, X } from 'lucide-react'
import { money } from '../lib/format'

type PreviewItem={id:string;environment:string|null;description:string;quantity:number;sale_total:number;affects_total:boolean;family:{name:string}|null}
type PreviewBudget={display_number:string;current_revision:number;created_at:string;valid_until:string|null;payment_terms:string|null;delivery_terms:string|null;notes:string|null;subtotal:number;discount:number;total:number}
const date=(value:string|null)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'A definir'

export function BudgetPreview({budget,items,clientName,clientAddress,onClose}:{budget:PreviewBudget;items:PreviewItem[];clientName:string;clientAddress?:string;onClose:()=>void}){
 return <div className="preview-backdrop"><div className="client-preview-shell"><div className="preview-toolbar"><div><strong>Prévia do orçamento para o cliente</strong><span>Esta é a mesma versão usada na impressão e no PDF.</span></div><button className="button secondary" onClick={()=>window.print()}><Printer/>Imprimir / salvar PDF</button><button className="icon-button" aria-label="Fechar prévia" onClick={onClose}><X/></button></div><article className="client-document"><header><div className="document-brand"><span>FK</span><div><strong>FÁBRIKA KRIATIVA</strong><small>Soluções personalizadas para ambientes</small></div></div><div className="document-number"><small>ORÇAMENTO</small><strong>{budget.display_number}</strong><span>Revisão {budget.current_revision} · {date(budget.created_at)}</span></div></header><section className="document-client"><div><small>CLIENTE</small><strong>{clientName}</strong>{clientAddress&&<span>{clientAddress}</span>}</div><div><small>PREVISÃO</small><strong>{budget.delivery_terms||'A definir'}</strong></div></section><section className="document-items">{items.length?items.map(item=><div className={`document-item ${item.affects_total?'':'option'}`} key={item.id}><div className="document-item-heading"><strong>{item.family?.name??'Item'}{item.environment?` · ${item.environment}`:''}</strong><strong>{money.format(Number(item.sale_total))}</strong></div><p>{item.description}</p><small>Quantidade: {Number(item.quantity).toLocaleString('pt-BR')}{!item.affects_total?' · Opção comercial - não incluída no total':''}</small></div>):<div className="document-empty">Nenhum item incluído neste orçamento.</div>}</section><section className="document-total"><div><span>Subtotal</span><strong>{money.format(Number(budget.subtotal))}</strong></div>{Number(budget.discount)>0&&<div><span>Desconto</span><strong>- {money.format(Number(budget.discount))}</strong></div>}<div className="grand-total"><span>Total</span><strong>{money.format(Number(budget.total))}</strong></div></section><footer><p><strong>Condição de pagamento:</strong> {budget.payment_terms||'A definir'}</p><p><strong>Validade:</strong> {date(budget.valid_until)}</p>{budget.notes&&<p><strong>Observações:</strong> {budget.notes}</p>}</footer></article></div></div>
}
