import { Plus, Trash2 } from 'lucide-react'
import { money } from '../lib/format'
import { optionFinalValue, standardItemPaymentOptions, type ItemPaymentOption } from '../lib/paymentOptions'
import './ItemPaymentOptions.css'

const blank=(position:number):ItemPaymentOption=>({position,description:'',adjustment_percent:0,observation:''})
export function ItemPaymentOptions({saleTotal,options,onChange}:{saleTotal:number;options:ItemPaymentOption[];onChange:(options:ItemPaymentOption[])=>void}){
 const update=(index:number,change:Partial<ItemPaymentOption>)=>onChange(options.map((item,current)=>current===index?{...item,...change}:item))
 return <section className="item-payment-options span-2"><header><div><strong>Opções comerciais do item</strong><small>Valores alternativos por condição de pagamento. Elas pertencem ao orçamento, são exibidas ao cliente e não alteram o financeiro.</small></div><div><button type="button" className="button secondary compact-button" onClick={()=>onChange(standardItemPaymentOptions())}>Usar opções padrão</button><button type="button" className="button secondary compact-button" onClick={()=>onChange([...options,blank(options.length+1)])}><Plus/>Adicionar opção</button></div></header>{options.length?<div className="payment-option-lines"><div className="payment-option-head"><span>Descrição da condição</span><span>% desconto/acréscimo</span><span>Valor final</span><span>Observação</span><span/></div>{options.map((option,index)=><div className="payment-option-line" key={option.id??index}><input aria-label={`Descrição da condição ${index+1}`} value={option.description} onChange={event=>update(index,{description:event.target.value})}/><input aria-label={`Desconto ou acréscimo ${index+1}`} type="number" step="0.01" value={option.adjustment_percent} onChange={event=>update(index,{adjustment_percent:Number(event.target.value)})}/><strong>{money.format(optionFinalValue(saleTotal,option.adjustment_percent))}</strong><input aria-label={`Observação da condição ${index+1}`} value={option.observation} onChange={event=>update(index,{observation:event.target.value})}/><button type="button" className="icon-button" aria-label={`Excluir opção ${index+1}`} onClick={()=>onChange(options.filter((_,current)=>current!==index))}><Trash2/></button></div>)}</div>:<p>Use as opções padrão ou inclua uma condição comercial.</p>}</section>
}
