import { Printer, X } from 'lucide-react'
import { money } from '../lib/format'
type OrderItem={id:string;snapshot:{environment?:string|null;description?:string;quantity?:number;sale_total?:number}}
type PreviewOrder={display_number:string;created_at:string;status:string;payment_terms:string|null;promised_date:string|null;client_address:string|null;total:number;client:{name:string;address:string|null;city:string|null}|null;budget:{display_number:string}|null;order_items:OrderItem[]}
const displayDate=(value:string|null)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'A confirmar'
export function OrderPreview({order,onClose,onEditDate,onConfigureReceivables}:{order:PreviewOrder;onClose:()=>void;onEditDate:()=>void;onConfigureReceivables:()=>void}){
 const address=order.client_address||[order.client?.address,order.client?.city].filter(Boolean).join(' · ')
 return <div className="preview-backdrop"><div className="client-preview-shell"><div className="preview-toolbar"><div><strong>Pedido para o cliente</strong><span>Versão final para impressão ou salvamento em PDF.</span></div>{order.status==='awaiting_finance'&&<button className="button primary" onClick={onConfigureReceivables}>Configurar recebimento</button>}<button className="button secondary" onClick={onEditDate}>Dados de entrega</button><button className="button secondary" onClick={()=>window.print()}><Printer/>Imprimir / salvar PDF</button><button className="icon-button" aria-label="Fechar pedido" onClick={onClose}><X/></button></div><article className="client-document"><header><div className="document-brand"><span>FK</span><div><strong>FÁBRIKA KRIATIVA</strong><small>Soluções personalizadas para ambientes</small></div></div><div className="document-number"><small>PEDIDO</small><strong>{order.display_number}</strong><span>Emitido em {displayDate(order.created_at)}</span></div></header><section className="document-client"><div><small>CLIENTE</small><strong>{order.client?.name??'Cliente não informado'}</strong>{address&&<span>{address}</span>}</div><div><small>ORÇAMENTO DE ORIGEM</small><strong>{order.budget?.display_number??'—'}</strong></div></section><div className="document-confirmation"><strong>Pedido confirmado</strong><span>Os itens abaixo correspondem à versão aprovada do orçamento.</span></div><section className="document-items">{order.order_items.map((item,index)=><div className="document-item" key={item.id}><div className="document-item-heading"><strong>{item.snapshot.environment||`Item ${index+1}`}</strong><strong>{money.format(Number(item.snapshot.sale_total||0))}</strong></div><p>{item.snapshot.description||'Descrição não informada'}</p><small>Quantidade: {Number(item.snapshot.quantity||0).toLocaleString('pt-BR')}</small></div>)}</section><section className="document-total"><div className="grand-total"><span>Total do pedido</span><strong>{money.format(Number(order.total))}</strong></div></section><footer><p><strong>Condição de pagamento:</strong> {order.payment_terms||'A definir'}</p><p><strong>Entrega combinada:</strong> {displayDate(order.promised_date)}</p></footer></article></div></div>
}
