import { useMemo, useState } from 'react'
import { X } from 'lucide-react'
import { useToast } from './ToastProvider'
import { supabase } from '../lib/supabase'
type Item={id:string;status:string;snapshot:{environment?:string|null;description?:string}}
type Props={organizationId:string;order:{id:string;display_number:string;order_items:Item[]};onClose:()=>void;onSaved:()=>Promise<void>}
const stages={preparing:'Em preparação',ready_to_schedule:'Pronto para agendar',scheduled:'Agendado',completed:'Concluído',pending_issue:'Com pendência'} as const
export function OrderOperation({organizationId,order,onClose,onSaved}:Props){
 const {show}=useToast(),active=order.order_items.filter(x=>x.status!=='cancelled'),[selected,setSelected]=useState(active.map(x=>x.id)),[stage,setStage]=useState<keyof typeof stages>('preparing'),[scheduled,setScheduled]=useState(''),[issue,setIssue]=useState(''),[saving,setSaving]=useState(false)
 const valid=selected.length>0&&(stage!=='scheduled'||Boolean(scheduled))&&(stage!=='pending_issue'||issue.trim().length>=5),all=useMemo(()=>selected.length===active.length,[selected,active.length])
 const toggle=(id:string)=>setSelected(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id])
 const save=async()=>{if(!supabase||saving||!valid)return;setSaving(true);const {error}=await supabase.rpc('update_order_items_operation',{org_id:organizationId,target_order_id:order.id,target_item_ids:selected,new_status:stage,new_scheduled_at:stage==='scheduled'?new Date(scheduled).toISOString():null,new_issue_reason:stage==='pending_issue'?issue:null});if(error)show('Não foi possível atualizar os itens do pedido.','error');else{show('Etapa aplicada aos itens selecionados.','success');await onSaved();onClose()}setSaving(false)}
 return <div className="dialog-backdrop"><div className="dialog"><header><div><span className="eyebrow">Operação do pedido</span><h2>{order.display_number}</h2><p>Atualize um ou vários itens ao mesmo tempo.</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="form-grid"><label className="checkbox-field span-2"><input type="checkbox" checked={all} onChange={()=>setSelected(all?[]:active.map(x=>x.id))}/>Selecionar todos</label><div className="span-2 operation-items">{active.map((item,index)=><label className="checkbox-field" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/><span><strong>{item.snapshot.environment||('Item '+(index+1))}</strong><small>{item.snapshot.description||'Sem descrição'} · {item.status}</small></span></label>)}</div><label className="field span-2">Nova etapa<select value={stage} onChange={e=>setStage(e.target.value as keyof typeof stages)}>{Object.entries(stages).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{stage==='scheduled'&&<label className="field span-2">Data e hora do agendamento<input type="datetime-local" required value={scheduled} onChange={e=>setScheduled(e.target.value)}/></label>}{stage==='pending_issue'&&<label className="field span-2">Motivo da pendência<input required minLength={5} value={issue} onChange={e=>setIssue(e.target.value)} placeholder="Informe o que precisa ser resolvido"/></label>}</div><footer><button className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={saving||!valid} onClick={()=>void save()}>{saving?'Salvando…':'Aplicar etapa'}</button></footer></div></div>
}
