import { useMemo, useState } from 'react'
import { AlertTriangle, X } from 'lucide-react'
import { useToast } from './ToastProvider'
import { money } from '../lib/format'
import { supabase } from '../lib/supabase'

export type PurchaseForConfirmation={id:string;display_number:string;mode:'immediate'|'made_to_order';status:string;total:number;supplier_id:string|null;external_number:string|null;ordered_at:string|null;supplier_due_date:string|null;payment_terms:string|null;purchase_items:{order_item:{order:{display_number:string;promised_date:string|null}|null}|null}[]}
type Supplier={id:string;name:string}
type Props={organizationId:string;purchase:PurchaseForConfirmation;suppliers:Supplier[];onClose:()=>void;onSaved:()=>Promise<void>}
const today=()=>new Date().toISOString().slice(0,10)

export function PurchaseConfirmation({organizationId,purchase,suppliers,onClose,onSaved}:Props){
 const {show}=useToast(),[supplier,setSupplier]=useState(purchase.supplier_id??''),[external,setExternal]=useState(purchase.external_number??''),[orderedAt,setOrderedAt]=useState(purchase.ordered_at??today()),[method,setMethod]=useState(purchase.payment_terms?.split(' · ').at(-1)??'PIX'),[installments,setInstallments]=useState(Number(purchase.payment_terms?.split('x')[0])||1),[due,setDue]=useState(purchase.supplier_due_date??''),[received,setReceived]=useState(today()),[reason,setReason]=useState(''),[confirmCancel,setConfirmCancel]=useState(false),[confirmReturn,setConfirmReturn]=useState(false),[returnReason,setReturnReason]=useState(''),[saving,setSaving]=useState(false)
 const customerDue=useMemo(()=>purchase.purchase_items.map(x=>x.order_item?.order?.promised_date).filter((x):x is string=>Boolean(x)).sort()[0]??null,[purchase]),orderNumber=purchase.purchase_items[0]?.order_item?.order?.display_number??'Pedido do cliente',late=Boolean(due&&customerDue&&due>customerDue)
 const finish=async(message:string)=>{show(message,'success');await onSaved();onClose()}
 const confirm=async()=>{if(!supabase||saving)return;setSaving(true);const {error}=await supabase.rpc('confirm_supplier_purchase',{org_id:organizationId,target_purchase_id:purchase.id,selected_supplier_id:supplier,new_external_number:external,new_ordered_at:orderedAt,new_payment_method:method,new_installment_count:installments});if(error)show('Não foi possível confirmar o pedido. Confira os dados.','error');else await finish('Pedido confirmado e contas a pagar geradas.');setSaving(false)}
 const saveDue=async()=>{if(!supabase||saving||!due)return;setSaving(true);const {error}=await supabase.rpc('set_purchase_supplier_due_date',{org_id:organizationId,target_purchase_id:purchase.id,new_supplier_due_date:due});if(error)show('Não foi possível atualizar a previsão.','error');else await finish('Previsão aplicada aos itens e às parcelas.');setSaving(false)}
 const receive=async()=>{if(!supabase||saving||!received)return;setSaving(true);const {error}=await supabase.rpc('receive_supplier_purchase',{org_id:organizationId,target_purchase_id:purchase.id,new_received_at:received});if(error)show('Não foi possível registrar o recebimento.','error');else await finish('Recebimento aplicado a todos os itens.');setSaving(false)}
 const cancel=async()=>{if(!supabase||saving||reason.trim().length<5)return;setSaving(true);const {error}=await supabase.rpc('cancel_supplier_purchase',{org_id:organizationId,target_purchase_id:purchase.id,new_reason:reason});if(error)show(error.message.includes('financial reversal')?'Há pagamento registrado. Faça a reversão financeira antes de cancelar.':'Não foi possível cancelar a compra.','error');else await finish('Compra cancelada, parcelas encerradas e itens devolvidos às necessidades.');setSaving(false)}
 const returnPurchase=async()=>{if(!supabase||saving||returnReason.trim().length<5)return;setSaving(true);const {error}=await supabase.rpc('return_received_purchase',{org_id:organizationId,target_purchase_id:purchase.id,new_reason:returnReason});if(error)show(error.message.includes('financial reversal')?'Há pagamento registrado. Estorne-o no Financeiro antes da devolução.':'Não foi possível registrar a devolução.','error');else await finish('Devolução registrada e itens liberados para nova compra.');setSaving(false)}
 const active=['draft','awaiting_delivery','delayed'].includes(purchase.status)
 return <div className="dialog-backdrop"><div className="dialog"><header><div><span className="eyebrow">Pedido ao fornecedor</span><h2>{purchase.display_number}</h2><p>{orderNumber} · {money.format(Number(purchase.total))}</p></div><button className="icon-button" onClick={onClose}><X/></button></header>
  {purchase.status==='draft'?<div className="form-grid"><label className="field span-2">Fornecedor<select required value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Selecione</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field">Número externo / Cód. interno<input required value={external} onChange={e=>setExternal(e.target.value)}/></label><label className="field">Data do pedido<input required type="date" value={orderedAt} onChange={e=>setOrderedAt(e.target.value)}/></label><label className="field">Forma de pagamento<select value={method} onChange={e=>setMethod(e.target.value)}><option>PIX</option><option>Transferência bancária</option><option>Boleto</option><option>Cartão de crédito</option><option>Cartão de débito</option><option>Dinheiro</option><option>A combinar</option></select></label><label className="field">Parcelas<input type="number" min="1" max="60" value={installments} onChange={e=>setInstallments(Math.max(1,Math.min(60,Number(e.target.value))))}/></label><p className="span-2 finance-note">Sob encomenda: vencimentos a partir da entrega confirmada. Compra imediata: PIX, dinheiro e débito ficam pagos na data da compra.</p></div>:purchase.mode==='made_to_order'&&active?<div className="form-grid"><label className="field span-2">Previsão de entrega do fornecedor<input required type="date" value={due} onChange={e=>setDue(e.target.value)}/></label>{customerDue&&<p className="span-2 finance-note">Entrega combinada com o cliente: {new Date(`${customerDue}T12:00:00`).toLocaleDateString('pt-BR')}</p>}{late&&<p className="span-2 inline-warning"><AlertTriangle/>A entrega do fornecedor ultrapassa a data combinada com o cliente.</p>}<label className="field span-2">Data efetiva do recebimento<input type="date" max={today()} value={received} onChange={e=>setReceived(e.target.value)}/></label></div>:<p className="finance-note">{purchase.status==='cancelled'?'Compra cancelada.':'Compra concluída.'}</p>}
  {confirmCancel&&<div className="inline-confirm"><div><strong>Cancelar esta compra?</strong><span>Parcelas pendentes serão canceladas e os itens voltarão às necessidades.</span></div><label className="field"><span>Motivo</span><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Informe o motivo"/></label><button className="button secondary" onClick={()=>setConfirmCancel(false)}>Manter</button><button className="button danger" disabled={saving||reason.trim().length<5} onClick={()=>void cancel()}>Confirmar cancelamento</button></div>}
  {confirmReturn&&<div className="inline-confirm"><div><strong>Registrar devolução?</strong><span>As parcelas pendentes serão canceladas e os itens voltarão a aguardar compra.</span></div><label className="field"><span>Motivo</span><input value={returnReason} onChange={e=>setReturnReason(e.target.value)} placeholder="Informe o motivo"/></label><button className="button secondary" onClick={()=>setConfirmReturn(false)}>Manter recebimento</button><button className="button danger" disabled={saving||returnReason.trim().length<5} onClick={()=>void returnPurchase()}>Confirmar devolução</button></div>}
  <footer>{active&&!confirmCancel&&<button className="button danger footer-left" onClick={()=>setConfirmCancel(true)}>Cancelar compra</button>}{purchase.status==='completed'&&!confirmReturn&&<button className="button danger footer-left" onClick={()=>setConfirmReturn(true)}>Registrar devolução</button>}<button className="button secondary" onClick={onClose}>Fechar</button>{purchase.status==='draft'?<button className="button primary" disabled={saving||!supplier||!external||!orderedAt} onClick={()=>void confirm()}>Confirmar e gerar parcelas</button>:purchase.mode==='made_to_order'&&active?<><button className="button secondary" disabled={saving||!due} onClick={()=>void saveDue()}>Salvar previsão</button><button className="button primary" disabled={saving||!received} onClick={()=>void receive()}>Confirmar recebimento</button></>:null}</footer>
 </div></div>
}
