import { useMemo, useState } from 'react'
import { AlertTriangle, X } from 'lucide-react'
import { useToast } from './ToastProvider'
import { money } from '../lib/format'
import { supabase } from '../lib/supabase'

export type PurchaseForConfirmation={
  id:string;display_number:string;mode:'immediate'|'made_to_order';status:string;total:number
  supplier_id:string|null;external_number:string|null;ordered_at:string|null;supplier_due_date:string|null;payment_terms:string|null
  purchase_items:{order_item:{order:{display_number:string;promised_date:string|null}|null}|null}[]
}
type Supplier={id:string;name:string}
type Props={organizationId:string;purchase:PurchaseForConfirmation;suppliers:Supplier[];onClose:()=>void;onSaved:()=>Promise<void>}
const today=()=>new Date().toISOString().slice(0,10)

export function PurchaseConfirmation({organizationId,purchase,suppliers,onClose,onSaved}:Props){
 const {show}=useToast(),[supplier,setSupplier]=useState(purchase.supplier_id??''),[external,setExternal]=useState(purchase.external_number??''),[orderedAt,setOrderedAt]=useState(purchase.ordered_at??today()),[method,setMethod]=useState(purchase.payment_terms?.split(' · ').at(-1)??'PIX'),[installments,setInstallments]=useState(Number(purchase.payment_terms?.split('x')[0])||1),[due,setDue]=useState(purchase.supplier_due_date??''),[saving,setSaving]=useState(false)
 const customerDue=useMemo(()=>purchase.purchase_items.map(x=>x.order_item?.order?.promised_date).filter((x):x is string=>Boolean(x)).sort()[0]??null,[purchase])
 const orderNumber=purchase.purchase_items[0]?.order_item?.order?.display_number??'Pedido do cliente'
 const late=Boolean(due&&customerDue&&due>customerDue)
 const confirm=async()=>{if(!supabase||saving)return;setSaving(true);const {error}=await supabase.rpc('confirm_supplier_purchase',{org_id:organizationId,target_purchase_id:purchase.id,selected_supplier_id:supplier,new_external_number:external,new_ordered_at:orderedAt,new_payment_method:method,new_installment_count:installments});if(error)show(error.code==='42501'?'Seu perfil não pode confirmar compras.':'Não foi possível confirmar o pedido. Confira os dados.','error');else{show('Pedido confirmado e contas a pagar geradas.','success');await onSaved();onClose()}setSaving(false)}
 const saveDue=async()=>{if(!supabase||saving||!due)return;setSaving(true);const {error}=await supabase.rpc('set_purchase_supplier_due_date',{org_id:organizationId,target_purchase_id:purchase.id,new_supplier_due_date:due});if(error)show('Não foi possível atualizar a previsão.','error');else{show('Previsão aplicada aos itens e às parcelas.','success');await onSaved();onClose()}setSaving(false)}
 return <div className="dialog-backdrop"><div className="dialog"><header><div><span className="eyebrow">Pedido ao fornecedor</span><h2>{purchase.display_number}</h2><p>{orderNumber} · {money.format(Number(purchase.total))}</p></div><button className="icon-button" onClick={onClose}><X/></button></header>{purchase.status==='draft'?<div className="form-grid"><label className="field span-2">Fornecedor<select required value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Selecione</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field">Número externo / Cód. interno<input required value={external} onChange={e=>setExternal(e.target.value)}/></label><label className="field">Data do pedido<input required type="date" value={orderedAt} onChange={e=>setOrderedAt(e.target.value)}/></label><label className="field">Forma de pagamento<select value={method} onChange={e=>setMethod(e.target.value)}><option>PIX</option><option>Transferência bancária</option><option>Boleto</option><option>Cartão de crédito</option><option>Cartão de débito</option><option>Dinheiro</option><option>A combinar</option></select></label><label className="field">Parcelas<input type="number" min="1" max="60" value={installments} onChange={e=>setInstallments(Math.max(1,Math.min(60,Number(e.target.value))))}/></label><p className="span-2 finance-note">Sob encomenda: vencimentos a partir da entrega confirmada. Compra imediata: PIX, dinheiro e débito ficam pagos na data da compra.</p></div>:purchase.mode==='made_to_order'?<div className="form-grid"><label className="field span-2">Previsão de entrega do fornecedor<input required type="date" value={due} onChange={e=>setDue(e.target.value)}/></label>{customerDue&&<p className="span-2 finance-note">Entrega combinada com o cliente: {new Date(`${customerDue}T12:00:00`).toLocaleDateString('pt-BR')}</p>}{late&&<p className="span-2 inline-warning"><AlertTriangle/>A entrega do fornecedor ultrapassa a data combinada com o cliente.</p>}</div>:<p className="finance-note">Compra imediata concluída, sem previsão de entrega.</p>}<footer><button className="button secondary" onClick={onClose}>Fechar</button>{purchase.status==='draft'?<button className="button primary" disabled={saving||!supplier||!external||!orderedAt} onClick={()=>void confirm()}>{saving?'Confirmando…':'Confirmar e gerar parcelas'}</button>:purchase.mode==='made_to_order'?<button className="button primary" disabled={saving||!due} onClick={()=>void saveDue()}>{saving?'Salvando…':'Salvar previsão para todos'}</button>:null}</footer></div></div>
}
