import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, X } from 'lucide-react'
import { useToast } from './ToastProvider'
import { money } from '../lib/format'
import { supabase } from '../lib/supabase'
import {extractPdfText} from '../lib/pdfText'
import {parseManufacturerText, type ParsedManufacturerDocument} from '../lib/manufacturerPdf'
import {installmentCount,validatePurchaseDocument} from '../lib/purchaseDocument'
import {purchaseDocumentPath} from '../lib/documents'

export type PurchaseForConfirmation={id:string;display_number:string;mode:'immediate'|'made_to_order';status:string;total:number;supplier_id:string|null;external_number:string|null;ordered_at:string|null;supplier_due_date:string|null;payment_terms:string|null;purchase_items:{description:string;order_item:{order:{display_number:string;promised_date:string|null}|null}|null}[]}
type Supplier={id:string;name:string}
type Attachment={id:string;original_name:string;storage_path:string}
type Props={organizationId:string;purchase:PurchaseForConfirmation;suppliers:Supplier[];requestedStatus?:string;onClose:()=>void;onSaved:()=>Promise<void>}
const today=()=>new Date().toISOString().slice(0,10)

export function PurchaseConfirmation({organizationId,purchase,suppliers,requestedStatus,onClose,onSaved}:Props){
 const {show}=useToast(),[supplier,setSupplier]=useState(purchase.supplier_id??''),[external,setExternal]=useState(purchase.external_number??''),[orderedAt,setOrderedAt]=useState(purchase.ordered_at??today()),[method,setMethod]=useState(purchase.payment_terms?.split(' · ').at(-1)??'PIX'),[installments,setInstallments]=useState(Number(purchase.payment_terms?.split('x')[0])||1),[due,setDue]=useState(purchase.supplier_due_date??''),[received,setReceived]=useState(today()),[reason,setReason]=useState(''),[confirmCancel,setConfirmCancel]=useState(requestedStatus==='cancelled'),[confirmReturn,setConfirmReturn]=useState(requestedStatus==='returned'),[returnReason,setReturnReason]=useState(''),[saving,setSaving]=useState(false)
 const [pdfFile,setPdfFile]=useState<File|null>(null),[pdfData,setPdfData]=useState<ParsedManufacturerDocument|null>(null),[pdfReading,setPdfReading]=useState(false),[attachments,setAttachments]=useState<Attachment[]>([])
 const customerDue=useMemo(()=>purchase.purchase_items.map(x=>x.order_item?.order?.promised_date).filter((x):x is string=>Boolean(x)).sort()[0]??null,[purchase]),orderNumber=purchase.purchase_items[0]?.order_item?.order?.display_number??'Pedido do cliente',late=Boolean(due&&customerDue&&due>customerDue)
 const validation=useMemo(()=>pdfData?validatePurchaseDocument(pdfData,purchase.purchase_items.map(item=>item.description)):null,[pdfData,purchase.purchase_items])
 useEffect(()=>{if(!supabase)return;void supabase.from('attachments').select('id,original_name,storage_path').eq('organization_id',organizationId).eq('entity_type','purchase').eq('entity_id',purchase.id).order('created_at',{ascending:false}).then(({data})=>setAttachments((data??[]) as Attachment[]))},[organizationId,purchase.id])
 const finish=async(message:string)=>{show(message,'success');await onSaved();onClose()}
 const readPdf=async(file?:File)=>{if(!file||!supabase)return;setPdfReading(true);try{const parsed=parseManufacturerText(await extractPdfText(file));const checked=validatePurchaseDocument(parsed,purchase.purchase_items.map(item=>item.description));setPdfFile(file);setPdfData(parsed);if(parsed.internalCode||parsed.externalNumber)setExternal(parsed.internalCode??parsed.externalNumber??'');if(parsed.documentDate)setOrderedAt(parsed.documentDate);if(parsed.paymentMethod)setMethod(parsed.paymentMethod);setInstallments(installmentCount(parsed.paymentTerms));show(checked.message,checked.valid?'success':'error')}catch{setPdfFile(null);setPdfData(null);show('Não foi possível ler este pedido do fornecedor.','error')}finally{setPdfReading(false)}}
 const archivePdf=async()=>{if(!supabase||!pdfFile||!pdfData)return true;const path=purchaseDocumentPath(organizationId,purchase.id,pdfFile.name);const uploaded=await supabase.storage.from('documents').upload(path,pdfFile,{contentType:'application/pdf',upsert:false});if(uploaded.error)return false;const registered=await supabase.rpc('register_purchase_attachment',{org_id:organizationId,target_purchase_id:purchase.id,object_path:path,file_name:pdfFile.name,content_type:'application/pdf',byte_size:pdfFile.size,extracted_data:pdfData});if(registered.error){await supabase.storage.from('documents').remove([path]);return false}return true}
 const confirm=async()=>{if(!supabase||saving||validation?.valid===false)return;setSaving(true);const {error}=await supabase.rpc('confirm_supplier_purchase',{org_id:organizationId,target_purchase_id:purchase.id,selected_supplier_id:supplier,new_external_number:external,new_ordered_at:orderedAt,new_payment_method:method,new_installment_count:installments});if(error)show('Não foi possível confirmar o pedido. Confira os dados.','error');else if(!await archivePdf()){show('Pedido confirmado e parcelas geradas, mas o PDF não pôde ser arquivado.','error');await onSaved();onClose()}else await finish('Pedido confirmado, documento arquivado e contas a pagar geradas.');setSaving(false)}
 const saveDue=async()=>{if(!supabase||saving||!due)return;setSaving(true);const {error}=await supabase.rpc('set_purchase_supplier_due_date',{org_id:organizationId,target_purchase_id:purchase.id,new_supplier_due_date:due});if(error)show('Não foi possível atualizar a previsão.','error');else await finish('Previsão aplicada aos itens e às parcelas.');setSaving(false)}
 const receive=async()=>{if(!supabase||saving||!received)return;setSaving(true);const {error}=await supabase.rpc('receive_supplier_purchase',{org_id:organizationId,target_purchase_id:purchase.id,new_received_at:received});if(error)show('Não foi possível registrar o recebimento.','error');else await finish('Recebimento aplicado a todos os itens.');setSaving(false)}
 const cancel=async()=>{if(!supabase||saving||reason.trim().length<5)return;setSaving(true);const {error}=await supabase.rpc('cancel_supplier_purchase',{org_id:organizationId,target_purchase_id:purchase.id,new_reason:reason});if(error)show(error.message.includes('financial reversal')?'Há pagamento registrado. Faça a reversão financeira antes de cancelar.':'Não foi possível cancelar a compra.','error');else await finish('Compra cancelada, parcelas encerradas e itens devolvidos às necessidades.');setSaving(false)}
 const returnPurchase=async()=>{if(!supabase||saving||returnReason.trim().length<5)return;setSaving(true);const {error}=await supabase.rpc('return_received_purchase',{org_id:organizationId,target_purchase_id:purchase.id,new_reason:returnReason});if(error)show(error.message.includes('financial reversal')?'Há pagamento registrado. Estorne-o no Financeiro antes da devolução.':'Não foi possível registrar a devolução.','error');else await finish('Devolução registrada e itens liberados para nova compra.');setSaving(false)}
 const active=['draft','awaiting_delivery','delayed'].includes(purchase.status)
 const openAttachment=async(attachment:Attachment)=>{if(!supabase)return;const {data,error}=await supabase.storage.from('documents').createSignedUrl(attachment.storage_path,300);if(error||!data?.signedUrl)show('Não foi possível abrir o documento.','error');else window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 return <div className="dialog-backdrop"><div className="dialog"><header><div><span className="eyebrow">Pedido ao fornecedor</span><h2>{purchase.display_number}</h2><p>{orderNumber} · {money.format(Number(purchase.total))}</p></div><button className="icon-button" onClick={onClose}><X/></button></header>
  {purchase.status==='draft'?<><div className="pdf-import"><label className={`pdf-drop ${pdfReading?'reading':''}`}><input type="file" accept="application/pdf,.pdf" onChange={e=>void readPdf(e.target.files?.[0])}/><strong>{pdfReading?'Lendo e conferindo…':'Anexar pedido do fornecedor em PDF'}</strong><span>O sistema confere os itens antes de preencher número, data e pagamento.</span></label>{validation&&<p className={validation.valid?'pdf-validation valid':'pdf-validation invalid'}>{validation.message}</p>}</div><div className="form-grid"><label className="field span-2">Fornecedor<select required value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Selecione</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field">Número externo / Cód. interno<input required value={external} onChange={e=>setExternal(e.target.value)}/></label><label className="field">Data do pedido<input required type="date" value={orderedAt} onChange={e=>setOrderedAt(e.target.value)}/></label><label className="field">Forma de pagamento<select value={method} onChange={e=>setMethod(e.target.value)}><option>PIX</option><option>Transferência bancária</option><option>Boleto</option><option>Cartão de crédito</option><option>Cartão de débito</option><option>Dinheiro</option><option>A combinar</option></select></label><label className="field">Parcelas<input type="number" min="1" max="60" value={installments} onChange={e=>setInstallments(Math.max(1,Math.min(60,Number(e.target.value))))}/></label><p className="span-2 finance-note">Sob encomenda: vencimentos a partir da entrega confirmada. Compra imediata: PIX, dinheiro e débito ficam pagos na data da compra.</p></div></>:purchase.mode==='made_to_order'&&active?<div className="form-grid"><label className="field span-2">Previsão de entrega do fornecedor<input required type="date" value={due} onChange={e=>setDue(e.target.value)}/></label>{customerDue&&<p className="span-2 finance-note">Entrega combinada com o cliente: {new Date(`${customerDue}T12:00:00`).toLocaleDateString('pt-BR')}</p>}{late&&<p className="span-2 inline-warning"><AlertTriangle/>A entrega do fornecedor ultrapassa a data combinada com o cliente.</p>}<label className="field span-2">Data efetiva do recebimento<input type="date" max={today()} value={received} onChange={e=>setReceived(e.target.value)}/></label></div>:<p className="finance-note">{purchase.status==='cancelled'?'Compra cancelada.':'Compra concluída.'}</p>}
  {attachments.length>0&&<div className="document-links"><strong>Documentos anexados</strong>{attachments.map(attachment=><button key={attachment.id} onClick={()=>void openAttachment(attachment)}>{attachment.original_name}</button>)}</div>}
  {confirmCancel&&<div className="inline-confirm"><div><strong>Cancelar esta compra?</strong><span>Parcelas pendentes serão canceladas e os itens voltarão às necessidades.</span></div><label className="field"><span>Motivo</span><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Informe o motivo"/></label><button className="button secondary" onClick={()=>setConfirmCancel(false)}>Manter</button><button className="button danger" disabled={saving||reason.trim().length<5} onClick={()=>void cancel()}>Confirmar cancelamento</button></div>}
  {confirmReturn&&<div className="inline-confirm"><div><strong>Registrar devolução?</strong><span>As parcelas pendentes serão canceladas e os itens voltarão a aguardar compra.</span></div><label className="field"><span>Motivo</span><input value={returnReason} onChange={e=>setReturnReason(e.target.value)} placeholder="Informe o motivo"/></label><button className="button secondary" onClick={()=>setConfirmReturn(false)}>Manter recebimento</button><button className="button danger" disabled={saving||returnReason.trim().length<5} onClick={()=>void returnPurchase()}>Confirmar devolução</button></div>}
  <footer>{active&&!confirmCancel&&<button className="button danger footer-left" onClick={()=>setConfirmCancel(true)}>Cancelar compra</button>}{purchase.status==='completed'&&!confirmReturn&&<button className="button danger footer-left" onClick={()=>setConfirmReturn(true)}>Registrar devolução</button>}<button className="button secondary" onClick={onClose}>Fechar</button>{purchase.status==='draft'?<button className="button primary" disabled={saving||!supplier||!external||!orderedAt||validation?.valid===false} onClick={()=>void confirm()}>Confirmar e gerar parcelas</button>:purchase.mode==='made_to_order'&&active?<><button className="button secondary" disabled={saving||!due} onClick={()=>void saveDue()}>Salvar previsão</button><button className="button primary" disabled={saving||!received} onClick={()=>void receive()}>Confirmar recebimento</button></>:null}</footer>
 </div></div>
}
